# Generated by Django 2.1.4 on 2018-12-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('created',), 'verbose_name': 'Person who works in a place'},
        ),
    ]
