# Generated by Django 2.1.4 on 2018-12-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20181206_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('created',)},
        ),
    ]
